workspaces = []
tags = ['', '', '', '', '', '', '']
layouts = ["MainAndVertStack", "CenterMainBalanced"]
layout_mode = "Tag"
insert_behavior = "Bottom"
scratchpad = []
disable_current_tag_swap = false
disable_tile_drag = true
focus_new_windows = true
focus_behaviour = "Sloppy"
sloppy_mouse_follows_focus = true
# max_window_width = 1920

window_rules = [
    { window_class = "Brave-browser", spawn_on_tag = 1 },
    { window_class = "Firefox", spawn_on_tag = 1 },
    { window_class = "Discord", spawn_on_tag = 3 },
    { window_class = "DesktopEditors", spawn_on_tag = 4 },
    { window_class = "Thunar", spawn_on_tag = 4 },
    { window_class = "Lutris", spawn_on_tag = 5 },
    { window_class = "Steam", spawn_on_tag = 5 },
    { window_class = "Gimp", spawn_on_tag = 6 },
    { window_class = "Kdenlive", spawn_on_tag = 6 },
    { window_class = "Virt-manager", spawn_on_tag = 7 },
]

modkey = "Mod4"
mousekey = "Mod4"

keybind = [
    { command = "SoftReload", value = "", modifier = ["modkey", "Shift"], key = "r" },

    { command = "CloseWindow", value = "", modifier = ["modkey"], key = "q" },
    { command = "ToggleFloating", value = "", modifier = ["modkey"], key = "c" },
    { command = "ToggleFullScreen", value = "", modifier = ["modkey"], key = "f" },

    { command = "NextLayout", value = "", modifier = ["modkey"], key = "Escape" },
    { command = "SwapTags", value = "", modifier = ["modkey"], key = "Tab" },
    { command = "IncreaseMainWidth", value = "5", modifier = ["modkey"], key = "Right" },
    { command = "DecreaseMainWidth", value = "5", modifier = ["modkey"], key = "Left" },

    { command = "FocusWorkspaceNext", value = "", modifier = ["modkey", "Control"], key = "l" },
    { command = "FocusWorkspacePrevious", value = "", modifier = ["modkey", "Control"], key = "h" },
    { command = "FocusNextTag", value = "", modifier = ["modkey"], key = "l" },
    { command = "FocusPreviousTag", value = "", modifier = ["modkey"], key = "h" },
    { command = "FocusWindowUp", value = "", modifier = ["modkey"], key = "k" },
    { command = "FocusWindowDown", value = "", modifier = ["modkey"], key = "j" },
    { command = "GotoTag", value = "1", modifier = ["modkey"], key = "ampersand" },
    { command = "GotoTag", value = "2", modifier = ["modkey"], key = "eacute" },
    { command = "GotoTag", value = "3", modifier = ["modkey"], key = "quotedbl" },
    { command = "GotoTag", value = "4", modifier = ["modkey"], key = "apostrophe" },
    { command = "GotoTag", value = "5", modifier = ["modkey"], key = "parenleft" },
    { command = "GotoTag", value = "6", modifier = ["modkey"], key = "minus" },
    { command = "GotoTag", value = "7", modifier = ["modkey"], key = "egrave" },

    { command = "MoveWindowToNextWorkspace", value = "", modifier = ["modkey", "Shift", "Control"], key = "l" },
    { command = "MoveWindowToPreviousWorkspace", value = "", modifier = ["modkey", "Shift", "Control"], key = "h" },
    # { command = "MoveWindowToNextTag", value = "", modifier = ["modkey", "Shift"], key = "l" },
    # { command = "MoveWindowToPreviousTag", value = "", modifier = ["modkey", "Shift"], key = "h" },
    { command = "MoveWindowUp", value = "", modifier = ["modkey", "Shift"], key = "k" },
    { command = "MoveWindowDown", value = "", modifier = ["modkey", "Shift"], key = "j" },
    { command = "MoveToTag", value = "1", modifier = ["modkey", "Shift"], key = "ampersand" },
    { command = "MoveToTag", value = "2", modifier = ["modkey", "Shift"], key = "eacute" },
    { command = "MoveToTag", value = "3", modifier = ["modkey", "Shift"], key = "quotedbl" },
    { command = "MoveToTag", value = "4", modifier = ["modkey", "Shift"], key = "apostrophe" },
    { command = "MoveToTag", value = "5", modifier = ["modkey", "Shift"], key = "parenleft" },
    { command = "MoveToTag", value = "6", modifier = ["modkey", "Shift"], key = "minus" },
    { command = "MoveToTag", value = "7", modifier = ["modkey", "Shift"], key = "egrave" },
]
