#!/usr/bin/env bash

INTERFACE=/sys/class/power_supply/BAT0/

percent="$(cat "$INTERFACE/capacity")"

class="icon-danger"
if [[ "$percent" -eq 100 ]]; then
	class="icon-variable-success"
elif [[ "$percent" -gt 40 ]]; then
	class="icon-variable-primary"
elif [[ "$percent" -gt 20 ]]; then
	class="icon-variable-warning"
fi

if [[ "$(cat "$INTERFACE/status")" = "Charging" ]]; then
	if [[ "$percent" -eq 100 ]]; then
		icon=""
	elif [[ "$percent" -gt 90 ]]; then
		icon=""
	elif [[ "$percent" -gt 80 ]]; then
		icon=""
	elif [[ "$percent" -gt 60 ]]; then
		icon=""
	elif [[ "$percent" -gt 40 ]]; then
		icon=""
	elif [[ "$percent" -gt 30 ]]; then
		icon=""
	else
		icon=""
	fi
else
	if [[ "$percent" -eq 100 ]]; then
		icon=""
	elif [[ "$percent" -gt 90 ]]; then
		icon=""
	elif [[ "$percent" -gt 80 ]]; then
		icon=""
	elif [[ "$percent" -gt 70 ]]; then
		icon=""
	elif [[ "$percent" -gt 60 ]]; then
		icon=""
	elif [[ "$percent" -gt 50 ]]; then
		icon=""
	elif [[ "$percent" -gt 40 ]]; then
		icon=""
	elif [[ "$percent" -gt 30 ]]; then
		icon=""
	elif [[ "$percent" -gt 20 ]]; then
		icon=""
	elif [[ "$percent" -gt 10 ]]; then
		icon=""
	else
		icon=""
	fi
fi

echo "{ \"percent\": \"$percent\", \"class\": \"$class\", \"icon\": \"$icon\" }"
