#!/usr/bin/env bash

playerctl -F metadata --format '{ #@#status#@#: #@#{{status}}#@#, #@#title#@#: #@#{{title}}#@#, #@#position#@#: #@#{{position}}#@#, #@#duration#@#: #@#{{mpris:length}}#@#, #@#time#@#: #@#{{duration(position)}} / {{duration(mpris:length)}}#@# }' | while read -r line; do
    line_no_quotes="$(echo "${line//\"/\\\"}")"
    echo "${line_no_quotes//#@#/\"}"
done
