#!/usr/bin/env bash

set -e

WIFI_DEVICE="wlan0"
ETHERNET_DEVICE="enp7s0"

on_change() {
    icon="睊"

    case "$(nmcli -g CONNECTIVITY general)" in
        "full")
            class="icon-variable-primary"
            ;;
        "limited")
            class="icon-variable-warning"
            ;;
        "none")
            class="icon-variable-gray"
            ;;
    esac

    if [[ "$(cat /sys/class/net/$ETHERNET_DEVICE/operstate)" = "up" ]]; then
        device="$ETHERNET_DEVICE"

        icon=""
    else
        device="$WIFI_DEVICE"

        if [[ -n "$(rfkill list wlan | awk '/Soft blocked: no/')" ]]; then
            icon="直"
        fi
    fi

    if [[ "$(cat /sys/class/net/$device/operstate)" = "up" ]]; then
        connection="$(nmcli -t connection show --active | awk -F ':' -v device=$device '$0~device { print $1 }')"
    else
        connection="No connection"
    fi

    echo "{ \"device\": \"$device\", \"connection\": \"$connection\", \"class\": \"$class\", \"icon\": \"$icon\" }"
}

on_change
nmcli monitor | while read -r line
do
    on_change
done
