#!/usr/bin/env bash

TERMINAL=alacritty

case $1 in
    "bluetooth")
        blueman-manager
        ;;
    "launcher")
        $HOME/.config/rofi/scripts/app-menu.sh
        ;;
    "network")
        $TERMINAL -e nmtui
        ;;
    "torrents")
        $TERMINAL -e tremc
        ;;
    "updates")
        $TERMINAL -e bash -c "paru -Syu; echo Done - Press enter to exit...; read _"
        ;;
    "volume")
        pavucontrol
        ;;
esac
