#!/usr/bin/env bash

set -e

on_change() {
    percent="0"
    class="icon--disabled--variable"

    percent=$(amixer -D pulse sget Master | awk -F '[][]' '/Left:/{ print $2 }' | tr -d %)

    if [[ $percent -ge 50 ]]; then
        icon="墳"
    elif [[ $percent -gt 0 ]]; then
        icon="奔"
    else
        icon="奄"
    fi

    if [[ $(amixer -D pulse sget Master | awk -F '[][]' '/Left:/{ print $4 }') = "on" ]]; then
        class="icon--primary--variable"
    else
        icon="婢"
    fi

    echo "{ \"percent\": \"$percent\", \"class\": \"$class\", \"icon\": \"$icon\" }"
}

on_change
pactl subscribe | while read -r line; do
    if [[ "$line" = "Event 'change' on sink"* ]]; then
        on_change
    fi
done
