#!/usr/bin/env bash

TERMINAL=alacritty

case $1 in
    "launcher")
        $HOME/.config/rofi/scripts/appmenu.sh
        ;;
    "torrents")
        $TERMINAL -e tremc
        ;;
    "updates")
        $TERMINAL -e yay -Syu
        ;;
    "tray")
        trayer --edge top --align right --distance 44 --widthtype pixel --width 80 --heighttype request --padding 8 --tint 0x00FF00FF
        ;;
esac
