#!/usr/bin/env bash
export SCRIPTPATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

sleep 1

EWW="eww"

# start eww daemon
$EWW daemon

index=0
leftwm-state -q -n -t $SCRIPTPATH/liquid/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  $EWW open --screen "$index" "bar$index"
  index=$((index+1))
done
