#!/usr/bin/env bash
export SCRIPTPATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

EWW="eww"

# start eww daemon
$EWW daemon

xrandr --listmonitors | tail -n +2 | awk '{print substr($1, 1, length($1)-1)}' | while read -r monitor; do
  $EWW open --screen $monitor bar$monitor
done
