#!/usr/bin/env bash
export SCRIPTPATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

sleep 3

pkill eww

# start eww daemon
eww daemon

monitors=("eDP-1" "DP-1")

index=0
leftwm-state -q -n -t $SCRIPTPATH/liquid/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  eww open --screen "${monitors[$index]}" "bar$index"
  index=$((index+1))
done
