#!/usr/bin/env bash

icon="󰂲"
enabled="false"
connection="Off"
connections_count="0"

if [[ -n "$(rfkill list bluetooth | awk '/Soft blocked: no/')" ]]; then
	icon="󰂯"
	enabled="true"
	connection="No connections"
	connections_count="$(bluetoothctl devices Connected | wc -l)"

	if [[ "$connections_count" -gt 0 ]]; then
		icon="󰂱"

		if [[ "$connections_count" -eq 1 ]]; then
			connection="$(bluetoothctl devices Connected | awk '{$1=$2=""; sub(/^ +/, "", $0); print}')"
		else
			connection="$connections_count devices"
		fi
	fi
fi

jq -Mcn \
	--arg connection "$connection" \
	--argjson enabled "$enabled" \
	--arg icon "$icon" \
	'{
        connection: $connection,
        enabled: $enabled,
        icon: $icon
    }'
