#!/usr/bin/env bash

PREVIOUS_VALUE=""

on_change() {
	state=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)

	muted=$(echo "$state" | grep MUTED)
	percent=$(echo "$state" | awk '{ print $2, "* 100 / 1" }' | bc)

	if [[ $percent -ge 50 ]]; then
		icon="󰕾"
	elif [[ $percent -gt 0 ]]; then
		icon="󰖀"
	else
		icon="󰕿"
	fi

	if [[ -z $muted ]]; then
		muted="false"
	else
		muted="true"
		icon="󰖁"
	fi

	VALUE=$(
		jq -Mcn \
			--arg icon "$icon" \
			--argjson muted "$muted" \
			--argjson percent "$percent" \
			'{
                icon: $icon,
                muted: $muted,
                percent: $percent
            }'
	)

	if [[ "$VALUE" == "$PREVIOUS_VALUE" ]]; then
		return 0
	fi

	PREVIOUS_VALUE="$VALUE"

	echo "$VALUE"
}

on_change
pw-mon -N | while read -r line; do
	if [[ "$line" == "changed"* ]]; then
		on_change
	fi
done
